server:
  port: 8082

spring:
  application:
    name: GOODS

eureka:
  instance:
    prefer-ip-address: true
    instance-id: goods-api-8082
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址